DROP TABLE IF EXISTS maps CASCADE;
CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  center VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT
);
